name: redpanda
services:
  producer:
    public: true
    image: okteto.dev/kafka-producer
    build: producer
    ports:
      - 8080
  consumer:
    image: okteto.dev/kafka-consumer
    build: consumer
  kafdrop:
    public: true
    image: obsidiandynamics/kafdrop:3.28.0-SNAPSHOT
    ports:
      - 9000
    environment:
      - KAFKA_BROKERCONNECT=redpanda:9092
      - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
  redpanda:
    image: vectorized/redpanda
    command:
    - /usr/bin/rpk
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
    - --
    - --kernel-page-cache
    - '1'
    ports:
      - 9092
    volumes:
      - /var/lib/redpanda/data
